import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoutButton from "@/components/logout-button";
import Link from "next/link";
import { getMe } from "@/actions/user.action";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getMe()
  console.log({ user });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="py-2 flex justify-between gap-2 w-full max-w-5xl mx-auto">
          <div className="py-2 flex gap-2">
            <Link href={'/profile'} className="hover:underline">Profile</Link>
            <Link href={'/admin'} className="hover:underline">Admin</Link>
          </div>
          {user ? (
            <LogoutButton />
          ) : (
            <Link href={'/login'} className=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-4 rounded">Login</Link>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
